#!/usr/bin/env groovy

stage 'Checking connectivity'

node {
    deleteDir()
    checkout scm

    wrap([$class: 'AnsiColorBuildWrapper', colorMapName: 'xterm']){
        ansiblePlaybook(
            playbook: '/Users/lonny/Documents/Ansible_Book/playbooks/pipeline_yml/ping.yml',
            inventory: '/Users/lonny/Documents/Ansible_Book/playbooks/inventory/hosts',
            extras: '-e url=www.baidu.com',
            colorized: true
        )
    }
    input '是否继续?'
}

stage 'checking date time'

node {
    wrap([$class: 'AnsiColorBuildWrapper', colorMapName: 'xterm']){
        ansiblePlaybook(
            playbook: '/Users/lonny/Documents/Ansible_Book/playbooks/pipeline_yml/time.yml',
            inventory: '/Users/lonny/Documents/Ansible_Book/playbooks/inventory/hosts',
            colorized: true
        )
    }
}

stage 'checking crond'

node {
    wrap([$class: 'AnsiColorBuildWrapper', colorMapName: 'xterm']){
        ansiblePlaybook(
            playbook: '/Users/lonny/Documents/Ansible_Book/playbooks/pipeline_yml/crontab.yml'
            inventory: '/Users/lonny/Documents/Ansible_Book/playbooks/inventory/hosts',
            colorized: true
        )
    }
}