pipeline {
  agent { label 'docker' }
  environment {
        IMAGE = readMavenPom().getArtifactId()    //Use Pipeline Utility Steps
        VERSION = readMavenPom().getVersion()
    }
  options {
    ansiColor colorMapName: 'XTerm'
  }
  stages {
    stage('Build') {
      steps {
        sh "echo ${IMAGE}:${VERSION}"
      }
    }
  }
}